from system import utils as u
import random
import string
import smtplib
from email.mime.text import MIMEText


# Call in User Flow
def random_string(length):
    '''
    Generate random key that is later sent to user via email to validate his/her identity
    :param length: length of random string (int)
    :return: random string (str)
    '''
    letters = string.ascii_lowercase + string.digits
    random_string = ''.join(random.choice(letters) for i in range(length))
    return random_string


# important to call the random_string function and assign it to a global variable to later compare it
# random_string_password_reset = random_string(8)


def send_mail_password_reset(user_email, random_string):
    '''
    Sends a mail to user_email incl. random_string
    :param user_email: mail of user
    :param random_string: random_string generated by random_string function
    :return: send a mail to user_email
    '''
    # Establish Mail Server
    smtp_object = smtplib.SMTP('smtp.gmail.com', 587)
    smtp_object.ehlo()

    # Encryption
    smtp_object.starttls()

    # Login to Gmail
    email = 'e.health.comp0066@gmail.com'
    # password to above mentioned gmail address (please do not share with 3rd parties)
    # normally this password would be protected and not be accessible to an user.
    password = "&/h'Jj'}c)Y6?T@%:^Y["
    smtp_object.login(email, password)

    # Define Mail parameters
    from_address = 'e.health.comp0066@gmail.com'
    to_address = '{}'.format(user_email)
    message = MIMEText("""Hi, your code to reset your password is:\n{}""".format(random_string))
    message['Subject'] = 'Password Reset for E-HEALTH'
    message['To'] = '{}'.format(user_email)

    # Send Mail
    smtp_object.sendmail(from_address, to_address, message.as_string())


# user_email = input('Please input your email address:')
# user_email = 'manuel.buri@gmail.com'
# user_type = 'patient'

# Call in User Flow
def send_code_to_registered_user(user_type, user_email, random_string_password_reset):
    # input mail and check if in database
    patient_email_query = """
        SELECT
            {}_id,
            {}_email
        FROM
            {}
        WHERE
            {}_email = '{}';""".format(user_type, user_type, user_type, user_type, user_email)

    user_email_df = u.db_read_query(patient_email_query)

    # one could also do a function with the things below and above
    if user_email_df.empty:
        # there is no patient registered with this email address --> redirect to patient registration or
        # tell the user to go back with #
        print('There is no {} registered with this email address.'.format(user_type))

    else:
        # send email to user
        send_mail_password_reset(user_email, random_string_password_reset)
        print(
            'The code to reset your password was sent to your email address: {}.'
            '\nPlease check your mail inbox and spam folder.'.format(user_email))


# send_code_to_registered_user(user_type, user_email)

# Only help in utils
def compare_random_string(random_string_password_reset):
    '''
    Compare random_string_password_reset with random_string_user_input
    :return: True if random_string_user_input and random_string_password_reset match, else False
    '''
    random_string_match = False
    available_tries = 3
    while random_string_match == False and available_tries > 0:
        random_string_user_input = input("Please enter your string:")
        if random_string_user_input == random_string_password_reset:
            random_string_match = True
            print('Your code matched')
        else:
            available_tries = available_tries - 1
            print('The code you entered did not match. You have {} more tries'.format(available_tries))
    return random_string_match


# new_password = input('Please input your new password:')
# Call in User Flow
def change_password(user_type, user_email, new_password, random_string_password_reset):
    '''
    Updates password after the random_string match was validated.
    :return: Updated the password of the user in the database
    '''
    if compare_random_string(random_string_password_reset) == True:
        # Update database with new password
        update_password_query = """
            UPDATE
                {}
            SET
                {}_password = '{}'
            WHERE
                {}_email = '{}';""".format(user_type, user_type, new_password, user_type, user_email)

        u.db_execute(update_password_query)
        message = 'Your password has been successfully changed'

    else:
        message = 'Your password could not be changed because your code does not match'

    return message
# change_password(user_type)
